FROM node:18.7-alpine3.15

# Create app directory
RUN mkdir -p /usr/src/backend
WORKDIR /usr/src/backend

# Copy all source files
COPY ./apollo/ /usr/src/backend

RUN chown -R node:node /usr/src/backend

#Execute all following as node user
USER node

# Docker entrypoint
COPY docker-entrypoint.sh /usr/src/backend
ENTRYPOINT ["docker-entrypoint.sh"]

# Install the dependencies in the container, mirror the host
# volume, and skip installing again if a node_modules folder is present:
CMD [ -d "node_modules" ]  && npm run dev || npm ci && npm run dev